---
- hosts: nexus
  vars:
    ansible_become: yes
    ansible_become_method: sudo
  tasks:
    - name: Install Java
      shell: amazon-linux-extras install -y corretto8
    - name: Install Nexus OSS
      unarchive:
        src: nexus-3.35.0-02-unix.tar.gz
        dest: /opt
    - name: Delete old nexus
      shell: rm -rf /opt/nexus
    - name: Rename directory
      shell: mv -f /opt/nexus-3.35.0-02 /opt/nexus
    - name: Change owner nexus directory
      shell: find /opt/nexus -exec chown ec2-user:ec2-user {} \;
    - name: Change owner sonatype-work directory
      shell: find /opt/sonatype-work -exec chown ec2-user:ec2-user {} \;
    - name : Copy nexus service
      copy:
        src: nexus.service
        dest: /etc/systemd/system
    - name: Reload daemon
      systemd:
        daemon_reload: yes
    - name: Start nexus service
      systemd:
        name: nexus
        state: started
    - name: Enable nexus service
      systemd:
        name: nexus
        enabled: yes
